# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ProjectMailbox' do

pod 'AFNetworking'
pod 'Parse'
pod 'MMDrawerController', '~> 0.5.7'
pod 'JSQMessagesViewController'

end

target 'ProjectMailboxTests' do

end

target 'ProjectMailboxUITests' do

end

